<?php	$mes = date('m');	$dd = date('d');	$aa = date('Y');	$opciones = array();	$contenido_esp = '';	$contenido_eng = '';	if($accion=="Editar"):		$hid = mysql_real_escape_string($_GET['hid']);		$query_edit = "SELECT ce.idEntrada id, ce.titulo_esp, ce.resumen_esp, ce.contenido_esp, ce.titulo_eng, ce.resumen_eng, ce.contenido_eng, ce.slug, ce.tipo, ce.opciones, ce.orden, DAY(ce.fechaPublicacion) dd, MONTH(ce.fechaPublicacion) mm, YEAR(ce.fechaPublicacion) aa, ce.estatus, ce.mostrarEn, ce.keywords FROM ctlg_entradas ce WHERE ce.idEntrada='$hid' LIMIT 0,1";		$result_edit = mysql_query($query_edit);		if($result_edit and mysql_num_rows($result_edit)==1):			$row_edit = mysql_fetch_array($result_edit);			$nid = $row_edit['id'];			$mes = $row_edit['mm'];			$dd = $row_edit['dd'];			$aa = $row_edit['aa'];			$opciones = unserialize($row_edit['opciones']);			$contenido_esp = htmlspecialchars(stripslashes($row_edit["contenido_esp"]));			$contenido_eng = htmlspecialchars(stripslashes($row_edit["contenido_eng"]));		endif;	endif;?><div class="formulario">	<h2><a id="toggleForm" href="#toggleForm"><?php echo $accion?> <?php echo $tituloAccion?></a></h2>  
    <div id="form_addup" class="hide">
		<form action="procesos/proc-contenido.php" enctype="multipart/form-data" method="post">			<?php startPost(); ?>            <input type="hidden" name="id" value="<?php echo $row_edit['id']?>" />            <input type="hidden" name="url_ref" value="<?php echo $_SERVER['HTTP_REFERER']?>" />			<input type="hidden" name="tipo" value="<?php echo $tipo?>" />
			<div class="info-col">				<div class="info-col-cont mR300">
					<fieldset>						<legend>Espa&ntilde;ol</legend>						<p><label>T&iacute;tulo<br>						<input class="titulo" type="text" name="titulo_esp" value="<?php echo $row_edit['titulo_esp']?>"></label></p>						<p><label>Contenido</label></p>						<p><textarea class="jquery_ckeditor" name="contenido_esp" cols="" rows=""><?php echo $contenido_esp?></textarea></p>					</fieldset>										<fieldset>						<legend>Ingl&eacute;s</legend>						<p><label>T&iacute;tulo<br>						<input class="titulo" type="text" name="titulo_eng" value="<?php echo $row_edit['titulo_eng']?>"></label></p>												<p><label>Contenido</label></p>						<p><textarea class="jquery_ckeditor" name="contenido_eng" cols="" rows=""><?php echo $contenido_eng?></textarea></p>					</fieldset>
                </div><!--.info-col-cont-->
            </div><!--.info-col-->
            <div class="post-entry"> 				<div class="info-box">					<h3>Opciones</h3>					<div class="seccion">						<p><label><strong>Mostrar t&iacute;tulo</strong></label></p>						<p><label><input type="radio" name="opciones[mostrarTitulo]" value="0" <?php if($accion=="Agregar" or $opciones['mostrarTitulo']=='0') echo 'checked="checked"';?> /> No</label></p>						<p><label><input type="radio" name="opciones[mostrarTitulo]" value="1" <?php if($opciones['mostrarTitulo']=='1') echo 'checked="checked"';?> /> Si</label></p> 					</div><!--.seccion-->
                    <?php include("widgets/btn-publicacion.php")?>				</div><!--.info-box-->			</div><!--.post-entry-->			<div class="clearfix"></div>		</form>	</div><!--#form_addup--></div><!--.formulario-->
<?php	$estadoForm = ($accion=="Editar")?"muestraForm();":"escondeForm();";	$scriptFooter = "<script src=\"js/ckeditor/ckeditor.js\"></script>	<script src=\"js/ckeditor/adapters/jquery.js\"></script>	<script src=\"js/ckfinder/ckfinder.js\"></script>	<script>$(function(){ $estadoForm });</script>";?>