<?php	$mes = date('m');	$dd = date('d');	$aa = date('Y');	$opciones = array();
	if($accion=="Editar"):
		$hid = mysql_real_escape_string($_GET['hid']);
		$query_edit = "SELECT cs.idSlider id, cs.titulo, cs.estatus, DAY(cs.fechaPublicacion) dd, MONTH(cs.fechaPublicacion) mm, YEAR(cs.fechaPublicacion) aa, opciones FROM ctlg_sliders cs WHERE cs.idSlider='{$hid}' LIMIT 0,1";		$result_edit = mysql_query($query_edit);
		if($result_edit and mysql_num_rows($result_edit)==1):			$row_edit = mysql_fetch_array($result_edit);			$nid = $row_edit['id'];			$mes = $row_edit['mm'];			$dd = $row_edit['dd'];			$aa = $row_edit['aa'];			$opciones = unserialize($row_edit['opciones']);
		endif;	endif;?>
<div class="formulario">    <h2><a id="toggleForm" href="#toggleForm"><?php echo $accion?> Banner</a></h2> 
    <div id="form_addup" class="hide">        <form id="formBanners" action="procesos/proc-slider.php" enctype="multipart/form-data" method="post">            <?php startPost(); ?>
			<input type="hidden" name="url_ref" value="<?php echo $_SERVER['HTTP_REFERER']?>" />            <input type="hidden" name="id" value="<?php echo $row_edit['id']?>" />            <input type="hidden" name="tipo" value="slider" />
            <div class="info-col">                <div class="info-col-cont mR300">					<p><label>T&iacute;tulo                    <input class="titulo" id="titulo" name="titulo" type="text" value="<?php echo $row_edit['titulo']?>"/></label></p>					
					<div id="cont_imagenes">						<?php							$nid = $hid;							$query_imagenes = "SELECT idImagen id, nomArchivo, contenido, pie_esp resumen, url, orden, titulo FROM ctlg_imagenes WHERE idEntrada='$nid' AND tipo='imageSlide'";							$result_imagenes = mysql_query($query_imagenes);							if($result_imagenes and mysql_num_rows($result_imagenes)):								while($row_imagenes = mysql_fetch_array($result_imagenes)):									$nid_imagen = $row_imagenes['id'];									$contenido = htmlspecialchars(stripslashes($row_imagenes["contenido"]));									$resumen = htmlspecialchars(stripslashes($row_imagenes["resumen"]));?>									<div class="info-box to-delete">										<h3>Banner</h3>										<div class="seccion">											<p><label>Título: <span class="descripcion">[ ejemplo.: http://www.google.com/]</span>											<input class="titulo" name="imageSlide[edit][<?php echo $row_imagenes['id']?>][titulo]" type="text" value="<?php echo $row_imagenes['titulo']?>"/></label></p>																						<p><label>URL: <span class="descripcion">[ ejemplo.: http://www.google.com/]</span>											<input class="titulo" name="imageSlide[edit][<?php echo $row_imagenes['id']?>][url]" type="text" value="<?php echo $row_imagenes['url']?>"/></label></p>																					<?php												$ancho = "50%";												if($row_imagenes["nomArchivo"]!=""):													$nomFile = $nid_imagen.'_image_'.$row_imagenes["nomArchivo"];?>													<input type="hidden" name="tmp_nomArchivo" value="<?php echo $nomFile?>" />													<p><img src="<?php echo $carpeta_imagenes.$nomFile?>" width="<?php echo $ancho?>" /></p>											<?php												endif;?>																																	<p><label>Introducci&oacute;n<br>											<textarea name="imageSlide[edit][<?php echo $row_imagenes['id']?>][pie]" cols="" rows=""><?php echo $resumen?></textarea></label></p>											<p><label>Contenido<br>											<textarea class="jquery_ckeditor" name="imageSlide[edit][<?php echo $row_imagenes['id']?>][contenido]" cols="" rows=""><?php echo $contenido?></textarea></label></p>																						<p><label>Posicion: <span class="descripcion">[ ejemplo.: 1]</span>											<input class="titulo" name="imageSlide[edit][<?php echo $row_imagenes['id']?>][orden]" type="text" value="<?php echo $row_imagenes['orden']?>"/></label></p>
											<p><a class="delFile" href="procesos/proc-delete-archivo.php?hid=<?php echo $nid_imagen?>&haccion=eliminar&tipo=image">[Eliminar]</a></p>										</div>									</div>
							<?php								endwhile;							endif;?>						<div class="clearfix"></div>					</div><!--#cont_imagenes-->					<div id="cont-slider-original">						<div class="info-box">							<h3>Banner</h3>							<div class="seccion">								<p><label>Título:<br>								<input class="titulo" name="imageSlide[titulo][]" type="text" value=""/></label></p>								<p><label>URL: <span class="descripcion">[ ejemplo.: http://www.google.com/]</span>								<input class="titulo" name="imageSlide[url][]" type="text" value=""/></label></p>
								<p><label>Imagen: <input id="nomArchivo" name="imageSlide[]" type="file" /></label></p>
								<p><label>Introducci&oacute;n<br>								<textarea name="imageSlide[pie_esp][]" cols="" rows=""></textarea></label></p>								<p><label>Contenido<br>								<textarea class="jquery_ckeditor" name="imageSlide[contenido][]" cols="" rows=""></textarea></label></p>
								<p><label>Posicion: <span class="descripcion">[ ejemplo.: http://www.google.com/]</span>								<input class="titulo" name="imageSlide[orden][]" type="text" value=""/></label></p>							</div>						</div>					</div>					<div id="clones">					</div>
					<div class="cont-btn-pub">						<p><input class="btn_submit clone-element" type="button" data-clone="#cont-slider-original" data-cloneTo="#clones" value="Agragar Otra Imagen" /></p>					</div><!--.cont-btn-pub-->                </div><!--.info-col-cont-->            </div><!--.info-col-->
            <div class="post-entry">                <div class="info-box">                    <h3>Opciones</h3>								<?php include("widgets/fecha-publicacion.php")?>					<?php include("widgets/publicacion.php")?>					<?php include("widgets/btn-publicacion.php")?>                </div><!--.info-box-->            </div><!--.post-entry-->            <div class="clearfix"></div>        </form>    </div><!--#form_addup--></div><!--.formulario--><?php	$estadoForm = ($accion=="Editar")?"muestraForm();":"escondeForm();";	$scriptFooter = "		<script src=\"js/ckeditor/ckeditor.js\"></script>		<script src=\"js/ckeditor/adapters/jquery.js\"></script>		<script src=\"js/ckfinder/ckfinder.js\"></script>		<script>$(function(){ $estadoForm });</script>";?>