<?php	function getNombreMes($mes, $short=false){		$meses = array("1" =>"Enero", "2" =>"Febrero", "3" =>"Marzo", "4" =>"Abril", "5" =>"Mayo", "6" =>"Junio", "7" =>"Julio", "8" =>"Agosto", "9" =>"Septiembre", "10" =>"Octubre", "11" =>"Noviembre", "12" =>"Diciembre" );		$mesesShort = array("1" =>"Ene", "2" =>"Feb", "3" =>"Mar", "4" =>"Abr", "5" =>"May", "6" =>"Jun", "7" =>"Jul", "8" =>"Ago", "9" =>"Sep", "10" =>"Oct", "11" =>"Nov", "12" =>"Dic" );;
		if($short):			return $mesesShort[$mes];		else:			return $meses[$mes];		endif;	}
	function startPost() {	  echo '<input type="hidden" name="postID" value="'.md5(uniqid(rand(), true)).'">';	}
	function postBlock($postID) {		if(isset($_SESSION['postID'])) {			if($postID == $_SESSION['postID']) {				return false;			}else{				$_SESSION['postID'] = $postID;				return true;			}		}else{			$_SESSION['postID'] = $postID;			return true;			}	}		function esSpam($txt) {		$txt = strtolower($txt);		$spamWords = array ('[/url]', 						'adderall', 'adipex', 'allegra', 'alprazolam', 'ambien', 						'buy', 'bontril', 'buspar', 'butalbital',  						'cheap', 'carisoprodol', 'celebrex', 'celexa', 'cialis', 'cipro', 'claritin', 'codeine', 						'diazepam', 'diflucan', 						'effexor', 'ephedra', 'ephedrine', 'evista', 						'fioricet', 'flexeril', 'fosamax', 						'hydrocodone', 						'klonopin', 						'lasix', 'levitra', 'lipitor', 'lorazepam', 'lortab', 						'meridia', 						'neurontin', 'nexium', 'norvasc', 						'paxil', 'phentermine', 'plavix', 'prevacid', 'prilosec', 'propecia', 'prozac',  						'ringtones',						'sex', 'singulair', 'soma',						'tramadol', 'tenuate', 'testosterone', 'tylenol', 						'ultram', 						'valium', 'valtrex', 'viagra', 'vicodin', 'vioxx', 						'wellbutrin', 						'xanax', 'xenical', 						'zocor', 'zoloft', 'zyban', 'zyrtec', '</a>', '[/link]' );
		$spamCount = 0;		foreach($spamWords as $spamWord):			$spamCount +=  substr_count($txt, $spamWord);		endforeach;		return $spamCount;	}
	function esEmail($email = ""){	    return filter_var($email, FILTER_VALIDATE_EMAIL);	}	function is_empty($value) {	    return mysql_real_escape_string(!empty($value));	}		function cortaTexto($string, $limit, $break=".", $pad="...") {		if(strlen($string)>$limit):			if(false!==($breakpoint = strpos($string, $break, $limit))):				if($breakpoint < strlen($string)-1):					$string = substr($string, 0, $breakpoint) . $pad;				endif;			endif;		endif;		return $string;	}
	function getInfoPadres($id, $padres = array()){		$idioma = $_SESSION['idioma'];				$query = "SELECT idCat, titulo_{$idioma}, tipo, slug, idCatPadre FROM ctlg_categorias WHERE idCat='$id' AND idCatPadre != 0 LIMIT 0,1";		$result = mysql_query($query);		$num_items = mysql_num_rows($result);		if($result and $num_items):			$row = mysql_fetch_array($result);			$padres = getInfoPadres($row['idCatPadre'], $padres);
			array_push($padres, $row);		endif;
		return $padres;	}
	function getIdHijos($id=0, $hijos = array()){		$query = "SELECT cc.idCat id, (SELECT cc2.idCat FROM ctlg_categorias cc2 WHERE cc2.idCatPadre = cc.idCat LIMIT 0,1) num_hijos FROM ctlg_categorias cc WHERE cc.idCatPadre = '$id' AND cc.esPublic='1'";				$result = mysql_query($query);		$num_items = mysql_num_rows($result);
		if($result and $num_items):			while($row = mysql_fetch_array($result)):				$hijos = getIdHijos($row['id'], $hijos);				array_push($hijos, $row['id']);			endwhile;		endif;		return $hijos;	}		function getInfoUser($id){		$query = "SELECT cu.nom_user, cu.nombre, cu.apellido FROM ctlg_usuarios cu WHERE cu.id_usuario = '$id' LIMIT 0,1";		$result = mysql_query($query);		$num_items = mysql_num_rows($result);
		if($result and $num_items):			$info = mysql_fetch_array($result);		endif;		return $info;	}
	function getIdUser($nameUser){		$query = "SELECT cu.id_usuario FROM ctlg_usuarios cu WHERE cu.nom_user = '$nameUser' LIMIT 0,1";		$result = mysql_query($query);		$num_items = mysql_num_rows($result);
		if($result and $num_items):			$info = mysql_fetch_array($result);		endif;
		return $info['id_usuario'];	}
	function getTags($id){		$tags = array();		$query = "SELECT cte.idCat id, cc.titulo, cc.slug FROM ctlg_cats_entradas cte LEFT JOIN ctlg_categorias cc USING (idCat) WHERE cte.idEntrada='$id'";		$result = mysql_query($query);
		if($result and mysql_num_rows($result)):			while($row = mysql_fetch_array($result)):				$tags[] = $row;			endwhile;		endif;		return $tags;	}
	function getIdTag($tag){		$query = "SELECT cc.idCat id FROM ctlg_categorias cc WHERE cc.slug='$tag' AND cc.tipo='tag' LIMIT 0,1";		$result = mysql_query($query);		if($result):			$info = mysql_fetch_array($result);		endif;		return $info['id'];	}
	function printTags($tags){		if(is_array($tags)):			foreach($tags as $tag):				echo "<a href='tag/{$tag['slug']}/'>{$tag['titulo']}</a> ";			endforeach;		endif;	}	function curPageURL() {		$pageURL = 'http';		if ($_SERVER["HTTPS"] == "on"){			$pageURL .= "s";		}
		$pageURL .= "://";
		if ($_SERVER["SERVER_PORT"] != "80") {			$pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];		} else {			$pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];		}		return $pageURL;	}
	function getMenu_($id = 0, $submenus = true, $maxNivel = "-1", $menu = array(), $crumbs = array(), $profundidad = "1"){		$idioma = $_SESSION['idioma'];				$query = "			(				SELECT					cc.idCat id,					cc.titulo_{$idioma} titulo,					cc.tipo,					cc.slug,					(						SELECT count(cc2.idCat)						FROM ctlg_categorias cc2						WHERE cc2.idCatPadre = cc.idCat						AND cc2.idCatPadre!='0'						LIMIT 0, 1					) + (						SELECT count(ce2.idEntrada)						FROM ctlg_entradas ce2						LEFT JOIN ctlg_cats_entradas USING (idEntrada)						LIMIT 0, 1					) num_hijos,					cc.orden,					cc.opciones				FROM ctlg_categorias cc				WHERE cc.idCatPadre = '{$id}'				AND cc.estatus = '1' 				AND cc.idCatPadre!='0'				AND cc.tipo NOT IN ('skill')			)			UNION			(				SELECT					ce.idEntrada id,					ce.titulo_{$idioma} titulo,					ce.tipo,					ce.slug,					0 num_hijos,					ce.orden,					ce.opciones				FROM ctlg_entradas ce				LEFT JOIN ctlg_cats_entradas cce USING (idEntrada)				WHERE cce.idCat = '{$id}'				AND tipo IN ('page', 'link')				AND ce.estatus='1'				AND ce.fechaPublicacion<=NOW()				AND cce.idCat!='0'			)			ORDER BY orden ASC, titulo ASC, id DESC";		$result = mysql_query($query);		$num_items = mysql_num_rows($result);				if($result and $num_items):			$i = 0;			while($row = mysql_fetch_array($result)):				$class = "";				$opciones = unserialize($row['opciones']);				$href = (isset($opciones['url']) and $opciones['url']!= "")? $opciones['url'] : $row['slug'];
				if(is_array($crumbs)):					foreach($crumbs as $path):						if( ($path['tipo'] == $row['tipo'] and $path['id'] == $row['id']) ):							$class .= " actual ";							break;						endif;					endforeach;				endif;				$opciones = unserialize($row['opciones']);								if(isset($opciones['clase']) and $opciones['clase']!=""){					$numItemsClase = isset($opciones['clase'])?count($opciones['clase']):0;					if($numItemsClase):						foreach($opciones['clase'] as $clase):							$class .= $clase;						endforeach;					endif;				}				if($i==0):					$class .= " first ";				endif;				if($i==($num_items-1)):					$class .= " last ";				endif;
				$thisMenu = array(					"titulo" => $row['titulo'],					"clase" => $class,					"href" => $href,					"profundidad" => $profundidad,					"id" => $row['id'],					"tipo" => $row['tipo'],					"icono" => isset($row['icono'])?$row['icono']:""				);
				$maxNivel--;
				if($row['num_hijos'] and $submenus and $maxNivel != 0):					$profundidad++;					$thisMenu['submenu'] = getMenu_($row['id'], $submenus, $maxNivel, array(), $crumbs, $profundidad);					$profundidad--;				endif;				$maxNivel++;				$menu[] = $thisMenu;				$i++;            endwhile;		endif;		return $menu;	}
	function printMenu($menu, $wrapper="li", $wrapperSubNivel="ul", $separador=""){		$i = 0;		if(is_array($menu) and count($menu)):			foreach($menu as $item):				if($i != 0 and $separador !=""):?>					<<?php echo $wrapper?> class="separador-item"><?php echo $separador?></<?php echo $wrapper?>>			<?php				endif;								if(isset($item['submenu']) and  $item['submenu'] != NULL):					$item['clase'] .= ' childrens ';				endif;								?>				<<?php echo $wrapper?>>					<a href="<?php echo $item['href']?>" class="<?php echo $item['clase']?> <?php echo $item['href']?>"><span><?php echo $item['titulo'];?></span></a>				<?php					if(isset($item['submenu']) and  $item['submenu'] != NULL):?>						<<?php echo $wrapperSubNivel;?> class="nivel-<?php echo $item['profundidad']?>">							<?php printMenu($item['submenu'], $wrapper, $wrapperSubNivel, $separador);?>						</<?php echo $wrapperSubNivel;?>>				<?php					endif;?>				</<?php echo $wrapper?>>			<?php				$i++;			endforeach;		endif;	}
	function printMenuPrefix($menu, $prefix, $actual="", $wrapper="li", $wrapperSubNivel="ul", $separador=""){		$i = 0;		if(is_array($menu) and count($menu)):			foreach($menu as $item):				if($i != 0 and $separador !=""):?>					<<?php echo $wrapper?> class="separador-item"><?php echo $separador?></<?php echo $wrapper?>>			<?php				endif;?>				<<?php echo $wrapper?>>					<?php						if($item['submenu'] == NULL):?>							<a href="<?php echo $prefix?><?php echo $item['href']?>" class="smoothScroll <?php if($actual == $item['href']): echo "actual"; endif?> <?php echo $item['clase']?>">					<?php						else:?>							<span class="<?php echo $item['clase']?>">					<?php						endif;?>					<span><?php echo $item['titulo'];?></span>
					<?php						if($item['submenu'] == NULL):?>							</a>					<?php						else:?>							</span>					<?php						endif;?>					</<?php echo $wrapper?>>			<?php				$i++;			endforeach;		endif;	}	function getImagenesGaleria($id, $tipo){		$imagenes = array();		$idioma = $_SESSION['idioma'];		$query = "SELECT idImagen id, nomArchivo, estatus, pie_{$idioma} pie FROM ctlg_imagenes WHERE idEntrada = '{$id}' AND tipo = '$tipo'";		$result = mysql_query($query);
		if($result and mysql_num_rows($result)):			while($row = mysql_fetch_array($result)):				$imagenes[] = array(					"src" => "{$row['id']}_image_{$row['nomArchivo']}"				);			endwhile;		endif;				return $imagenes;	}
	function printFeaturedImages($imagenes, $opciones){		$path = $opciones['path'];		$extra = $opciones['extra'];				if(@is_array($imagenes) and count($imagenes) > 0):			$result = @array_reverse($imagenes);?>						<div class="featured">				<div class="flexslider">					<ul class="slides">						<?php							$i == 0;							while($row = @array_pop($result)):?>								<li>									<?php										if($row['url']!=""):?>											<a href="<?php echo $row['url']?>">									<?php										endif;?>										<img alt="" src="<?php echo $path?><?php echo $row['src']?><?php echo $extra?>">									<?php										if($row['url']!=""):?>											</a>									<?php										endif;?>								</li>						<?php							endwhile;?>					</ul>					<div class="clearfix"></div>				</div><!--.flexslider-->				<div class="clearfix"></div>			</div><!--.featured-->			<div class="clearfix"></div>	<?php		endif;	}
	function printGaleriaConThumbs($imagenes, $opciones){		$path = $opciones['path'];		$extra = $opciones['extra'];		$pathThumb = $opciones['pathThumb'];		$thumbExtra = $opciones['thumbExtra'];		
		if(@is_array($imagenes) and count($imagenes) > 0):			$result = @array_reverse($imagenes);			$resultThumbs = $result;?>						<div class="galeria-flexslider">				<div class="thumbs">					<ul class="slides">						<?php							while($row = @array_pop($resultThumbs)):?>								<li>									<img alt="" src="<?php echo $pathThumb?><?php echo $row['src']?><?php echo $thumbExtra?>">								</li>						<?php							endwhile;?>					</ul>				</div>
				<div class="portrait">					<ul class="slides">						<?php							while($row = @array_pop($result)):?>								<li>									<?php										if($row['url']!=""):?>											<a href="<?php echo $row['url']?>">									<?php										endif;?>										<img alt="" src="<?php echo $path?><?php echo $row['src']?><?php echo $extra?>">									<?php										if($row['url']!=""):?>											</a>									<?php										endif;?>								</li>						<?php							endwhile;?>					</ul>					<div class="clearfix"></div>				</div><!--.flexslider-->				<div class="clearfix"></div>			</div><!--.featured-->			<div class="clearfix"></div><?php		endif;	}		function printImages($imagenes, $opciones){		$path = $opciones['path'];		$extra = $opciones['extra'];				if(@is_array($imagenes) and count($imagenes) > 0):			$result = @array_reverse($imagenes);			while($row = @array_pop($result)):?>				<img alt="" src="<?php echo $path?><?php echo $row['src']?><?php echo $extra?>">		<?php			endwhile;		endif;	}		function setBaseURL($urlSite = ""){		if ($urlSite == ''):			if (isset($_SERVER['HTTP_HOST'])):				$base_url = isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off' ? 'https' : 'http';				$base_url .= '://'. $_SERVER['HTTP_HOST'];				$base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);			else:				$base_url = 'http://localhost/';			endif;						$urlSite = $base_url;		endif;				return $urlSite;	}	function getURLData($get){		return array_filter(explode("/", $get), 'is_empty');	}	function getMetaPage($id){		$idioma = $_SESSION['idioma'];		$query = "					SELECT ce.idEntrada id, ce.titulo_{$idioma} titulo, ce.resumen_{$idioma} resumen, ce.contenido_{$idioma} contenido, ce.tipo, DAY(ce.fechaPublicacion) dia, MONTH(ce.fechaPublicacion) mes, YEAR(ce.fechaPublicacion) anio, ce.opciones, (SELECT CONCAT(ci.idImagen,'_image_', ci.nomArchivo) nomArchivo FROM ctlg_imagenes ci WHERE ci.idEntrada=ce.idEntrada AND ci.tipo='featPage' LIMIT 0,1) imagen, slug, orden			FROM ctlg_entradas ce			WHERE ce.idEntrada='{$id}'			AND ce.estatus='1'			LIMIT 0,1";		$result = mysql_query($query);		if($result and mysql_num_rows($result)):			return mysql_fetch_array($result);		endif;		return NULL;	}
	function getMetaInfo($slug){		$idioma = $_SESSION['idioma'];		$query = "(			SELECT				cc.idCat id,				cc.idCatPadre,				cc.titulo_{$idioma} titulo,				cc.resumen_{$idioma} resumen,				cc.contenido_{$idioma} contenido,				cc.tipo,				'' dia,				'' mes,				'' anio,				cc.opciones,				'' idUser,				(					SELECT CONCAT(ci.idImagen,'_image_', ci.nomArchivo) nomArchivo					FROM ctlg_imagenes ci					WHERE ci.idEntrada=cc.idCat					AND ci.tipo='featSeccion'					LIMIT 0,1				) imagen,				slug,				fechaPublicacion,				orden			FROM ctlg_categorias cc			WHERE cc.slug='{$slug}'			AND cc.estatus='1'			LIMIT 0,1		) UNION (			SELECT				ce.idEntrada id, 				cce.idCat idCatPadre, 				ce.titulo_{$idioma} titulo,				ce.resumen_{$idioma} resumen,				ce.contenido_{$idioma} contenido,				ce.tipo, 				DAY(ce.fechaPublicacion) dia, 				MONTH(ce.fechaPublicacion) mes, 				YEAR(ce.fechaPublicacion) anio, 				ce.opciones, 				ce.idUser, 				(					SELECT CONCAT(ci.idImagen,'_image_', ci.nomArchivo) nomArchivo 					FROM ctlg_imagenes ci 					WHERE ci.idEntrada = ce.idEntrada 					AND ci.tipo = 'featPage' 					LIMIT 0,1				) imagen, 				slug, 				fechaPublicacion, 				orden 			FROM ctlg_entradas ce 			LEFT JOIN ctlg_cats_entradas cce USING (idEntrada)			WHERE ce.slug='{$slug}'			AND ce.estatus='1' 			LIMIT 0,1		)		LIMIT 0,1";		$result = mysql_query($query);		if($result and mysql_num_rows($result)):			return mysql_fetch_array($result);		endif;		return NULL;	}
	function get_post_custom($id){		$item = array();		$query = "SELECT llave, valor FROM ctlg_meta_entradas WHERE idEntrada={$id}";		$result = mysql_query($query);
		if($result and mysql_num_rows($result)):			while($row = mysql_fetch_array($result)):				$items[$row['llave']] = $row['valor'];			endwhile;		endif;				return $items;	}
	function getMultimedia($id, $tipo, $limite=""){		$items = array();		$idioma = $_SESSION['idioma'];		$query = "SELECT idImagen id, nomArchivo, url, pie_{$idioma} pie, opciones FROM ctlg_imagenes WHERE tipo='{$tipo}' AND idEntrada='{$id}' AND estatus='1' {$limite}";		$result = mysql_query($query);		$numItems = @mysql_num_rows($result);
		if($result and $numItems):			while($row = mysql_fetch_array($result)):				$items[] = $row;			endwhile;					endif;				return $items;
	}

	function getFeaturesImage($id, $tipo, $limite=""){		$items = array();		$idioma = $_SESSION['idioma'];		$query = "SELECT idImagen id, nomArchivo, url, pie_{$idioma} pie, opciones FROM ctlg_imagenes WHERE tipo='{$tipo}' AND idEntrada='{$id}' AND estatus='1' {$limite}";		$result = mysql_query($query);		$numItems = @mysql_num_rows($result);		if($result and $numItems):			while($row = mysql_fetch_array($result)):				$items[] = array(					"id" => $row['id'],					"nomArchivo" => $row['id']."_image_".$row['nomArchivo'],					"url" => $row['url'],					"opciones" => $row['opciones'],					"pie" => $row['pie'],				);			endwhile;					endif;		return $items;
	}
	function getBannerImage($limite=""){		$items = array();		$query = "SELECT idBanner id, nomArchivo, opciones, url FROM ctlg_banners WHERE tipo='banner' AND estatus='1' AND fechaPublicacion<=NOW() {$limite}";		$result = mysql_query($query);		$numItems = @mysql_num_rows($result);		if($result and $numItems):			while($row = mysql_fetch_array($result)):				$items[] = array(					"id" => $row['id'],					"nomArchivo" => $row['id']."_banner_".$row['nomArchivo'],					"url" => $row['url'],					"opciones" => $row['opciones']				);			endwhile;		endif;				return $items;
	}

	function getNextProject($thisId, $orden, $fechaPublicacion){		$idioma = $_SESSION['idioma'];				$query = "SELECT ce.idEntrada id, ce.titulo_{$idioma} titulo, ce.slug FROM ctlg_entradas ce WHERE ce.tipo='proyecto' AND ce.estatus='1' AND orden > $orden ORDER BY orden ASC LIMIT 0,1";		$result = mysql_query($query);
		if($result and mysql_num_rows($result)):			return mysql_fetch_array($result);		endif;				return NULL;	}	function getPrevProject($thisId, $orden, $fechaPublicacion){		$idioma = $_SESSION['idioma'];				$query = "SELECT ce.idEntrada id, ce.titulo_{$idioma} titulo, ce.slug FROM ctlg_entradas ce WHERE ce.tipo='proyecto' AND ce.estatus='1' AND orden < $orden ORDER BY orden DESC LIMIT 0,1";		$result = mysql_query($query);		if($result and mysql_num_rows($result)):			return mysql_fetch_array($result);		endif;		return NULL;	}
	function add_post_views($id){		$query = "INSERT INTO ctlg_meta_entradas(idEntrada, llave, valor) VALUES('{$id}', '_views', '1')";		$result = mysql_query($query);		return  ($result and mysql_affected_rows()) ? true : false;	}
	function update_post_views($id){		$query = "UPDATE ctlg_meta_entradas SET valor=valor+1 WHERE idEntrada='{$id}' AND llave='_views'";		$result = mysql_query($query);
		if($result and mysql_affected_rows()):			return true;		else:			return add_post_views($id);		endif;				return false;	}?>