<?php	session_start();	if(!isset($_SESSION['user']) || $_SESSION['user']['acceso']!='cpanel'):		header("Location:../");		exit();	endif;	require("../conexion.php");	require("../scripts/funciones.php");	require("../ubica_carpetas.php");	require("../scripts/gump.class.php");
	$gump = new GUMP();
	$_GET = $gump->sanitize($_GET);	$url_ref = $_SERVER['HTTP_REFERER'];	$carpetaUpload = "../".$carpeta_imagenes;	$carpetaThumbs = $carpetaUpload."thumbs/";	$idUser = $_SESSION['user']['idUser'];	$idCatPadre = $_POST['idCatPadre'];	$titulo_esp = $_POST['titulo_esp'];	$resumen_esp = $_POST['resumen_esp'];	$contenido_esp = $_POST['contenido_esp'];	$titulo_eng = $_POST['titulo_eng'];	$resumen_eng = $_POST['resumen_eng'];	$contenido_eng = $_POST['contenido_eng'];	$tipo = $_POST['tipo'];	$orden = $_POST['orden'];	$mostrarEn = $_POST['mostrarEn'];	$keywords = $_POST['keywords'];	$estatus = $_POST['estatus'];	$fechaPublicacion = $_POST['aa'] . "-" . $_POST['mes'] . "-" . $_POST['dd']." 00:00:00";	$slug = $_POST['preSlug'].quitarAcentos($titulo_esp);	$opciones = @serialize($_POST['opciones']);
	/*insert*/	if(!empty($_POST["add"]) && postBlock($_POST['postID'])):		if(!empty($titulo_esp)):			$queryAdd = "INSERT INTO ctlg_categorias(idCatPadre, titulo_esp, resumen_esp, contenido_esp, titulo_eng, resumen_eng, contenido_eng, slug, tipo, opciones, orden, fechaPublicacion, mostrarEn, keywords, estatus) VALUES('{$idCatPadre}', '{$titulo_esp}', '{$resumen_esp}', '{$contenido_esp}', '{$titulo_eng}', '{$resumen_eng}', '{$contenido_eng}', '{$slug}', '{$tipo}', '{$opciones}', '{$orden}', '{$fechaPublicacion}', '{$mostrarEn}', '{$keywords}', '{$estatus}')";			$resultAdd = mysql_query($queryAdd);			$nid = mysql_insert_id();
			if($resultAdd):				$mensaje = 'La informaci&oacute;n se guardo con exito';				$clase = 'exito';				$config = array(					"carpetaUpload" => $carpetaUpload,					"carpetaThumbs" => $carpetaThumbs				);				procesaImagenes($nid, $config);			else:				$error = mysql_error();				$mensaje = "La informaci&oacute;n no se pudo guardar. $error";				$clase = 'error';			endif;		else:			$mensaje = "Uno o m&aacute;s campos parecen estar vacios";			$clase = "alerta";		endif;		escribeBitacora($idUser, "[ins] tabla: ctlg_categorias, id: {$nid}, titulo: {$titulo}, tipo: {$tipo}");		$_SESSION['resultado'] = array(			"mensaje" => $mensaje,			"clase" => $clase		);	endif;	/*edit*/	if(!empty($_POST["edit"]) && postBlock($_POST['postID'])):		if(!empty($titulo_esp)):			$nid = $_POST['id'];			$query_edit = "UPDATE ctlg_categorias SET idCatPadre='{$idCatPadre}', titulo_esp='{$titulo_esp}', resumen_esp='{$resumen_esp}', contenido_esp='{$contenido_esp}', titulo_eng='{$titulo_eng}', resumen_eng='{$resumen_eng}', contenido_eng='{$contenido_eng}', slug='{$slug}', orden='{$orden}', mostrarEn='{$mostrarEn}', opciones='{$opciones}', fechaPublicacion='{$fechaPublicacion}', keywords='{$keywords}', estatus='{$estatus}' WHERE idCat='{$nid}'";			$result_edit = mysql_query($query_edit);			if($result_edit):				$mensaje = 'La informaci&oacute;n se actualizo con exito';				$clase = 'exito';				$config = array(					"carpetaUpload" => $carpetaUpload,					"carpetaThumbs" => $carpetaThumbs				);				procesaImagenes($nid, $config);			else:				$mensaje = "La informaci&oacute;n no se pudo actualizar";				$clase = 'error';			endif;		else:			$mensaje = "Uno o m&aacute;s campos parecen estar vacios";			$clase = "alerta";		endif;
		escribeBitacora($idUser, "[edit] tabla: ctlg_categorias, id: {$nid}, titulo: {$titulo}, tipo: {$tipo}");
		$_SESSION['resultado'] = array(			"mensaje" => $mensaje,			"clase" => $clase		);		$url_ref = $_POST['url_ref'];	endif;	/*delete*/	if(isset($_GET["haccion"]) && $_GET["haccion"]=="eliminar"):		$nid = mysql_real_escape_string($_GET['hid']);
		$query_del = "DELETE FROM ctlg_categorias WHERE idCat='{$nid}'";		$result_del = mysql_query($query_del);
		if($result_del):			$mensaje = "La informaci&oacute;n se elimino con exito";			$clase = 'exito';		else:			$error = mysql_error();			$mensaje = "La informaci&oacute;n no se pudo eliminar. $error";			$clase = 'error';		endif;		escribeBitacora($idUser, "[del] tabla: ctlg_categorias, id: {$nid}");		$_SESSION['resultado'] = array(			"mensaje" => $mensaje,			"clase" => $clase		);	endif;
	/*volvemos a la pagina*/	header("location:".$url_ref);?>