<?php	session_start();
	if(!isset($_SESSION['user']) || $_SESSION['user']['acceso'] != 'cpanel'):		header("Location:../");		exit();	endif;
	include("../conexion.php");	include("../scripts/funciones.php");	include("../ubica_carpetas.php");	$url_ref = $_SERVER['HTTP_REFERER'];		$login = $_POST['login'];	$nombre = $_POST['nombre'];	$apellido = $_POST['apellido'];	$password = $_POST['password'];	$password2 = $_POST['password2'];	$email = $_POST['email'];	$nomArchivo = $_FILES['nomArchivo']['name'][0];	$fecha = $_POST['fecha'];	$comentarios = $_POST['comentarios'];	$rol = $_POST['rol'];	$telefono = $_POST['telefono'];	$ciudad = $_POST['ciudad'];	$estado = $_POST['estado'];	$pais = $_POST['pais'];	$direccion = $_POST['direccion'];	/*insert*/	if(!empty($_POST["addUser"])):		if(!empty($login) && !empty($nombre) && !empty($apellido) && !empty($password) && !empty($password2) && !empty($email) && postBlock($_POST['postID'])):					$query = "SELECT idUser FROM ctlg_usuarios WHERE login='{$login}' LIMIT 0,1";			$result = mysql_query($query);
			if($result and mysql_num_rows($result)==0):				$password = sha1($password);
				$query = "INSERT INTO ctlg_usuarios(login, nombre, apellido, email, nomArchivo, fecha, comentarios, rol, telefono, ciudad, estado, pais, direccion, password) VALUES('{$login}', '{$nombre}', '{$apellido}', '{$email}', '{$nomArchivo}', '{$fecha}', '{$comentarios}', '{$rol}','{$telefono}', '{$ciudad}', '{$estado}', '{$pais}', '{$direccion}', '{$password}')";
				$result = mysql_query($query);				$nid = mysql_insert_id();
				if($result):					$mensaje = 'La informaci&oacute;n se guardo con exito';					$clase = 'exito';										if(!empty($nomArchivo)):						if(subirImagen('nomArchivo', "../".$carpeta_imagenes.'users/', $nid.'_')):							smart_resize_image("../".$carpeta_imagenes.'users/'.$nid.'_'.$nomArchivo, 192, 192, true, "../".$carpeta_imagenes.'users/'.$nid.'_'.$nomArchivo, false, false);						else:							$mensaje .= "<br/>La imagen no pudo ser guardada en el servidor";							$clase = "alerta";						endif;					endif;				else:					$mensaje = 'La informaci&oacute;n no se pudo guardar';					$clase = 'error';				endif;
			else:				$mensaje = "El nombre de usuario ya existe";				$clase = "alerta";			endif;		else:			$mensaje = "Uno o m&aacute;s campos parecen estar vacios";			$clase = "alerta";		endif;		$_SESSION['resultado'] = array(			"mensaje"=>$mensaje,			"clase"=>$clase		);	endif;
	/*edit*/	if(!empty($_POST["editUser"]) && !empty($nombre) && !empty($apellido) && !empty($email) and postBlock($_POST['postID'])):		$nid = $_POST['id'];		if(!empty($nomArchivo)):			@unlink($_POST['tmp_nomArchivo']);			$add_nomArchivo = ", nomArchivo='{$nomArchivo}'";		endif;		$add_password = (!empty($password)) ? ", password='".sha1($_POST['password'])."'" : "";		$query = "UPDATE ctlg_usuarios SET nombre='{$nombre}', apellido='{$apellido}', email='{$email}', rol='{$rol}', comentarios='{$comentarios}', pais='{$pais}', estado='{$estado}', ciudad='{$ciudad}', direccion='{$direccion}', fecha='{$fecha}', telefono='{$telefono}' $add_nomArchivo $add_password WHERE idUser='{$nid}'";		$result = mysql_query($query);		
		if($result):			$mensaje = 'La informaci&oacute;n se actualizo con exito';			$clase = 'exito';			if(!empty($nomArchivo)):				if(subirImagen('nomArchivo', "../".$carpeta_imagenes.'users/', $nid.'_')):					smart_resize_image("../".$carpeta_imagenes.'users/'.$nid.'_'.$nomArchivo, 192, 192, true, "../".$carpeta_imagenes.'users/'.$nid.'_'.$nomArchivo, false, false);				else:					$mensaje .= "<br/>La imagen no pudo ser guardada en el servidor";					$clase = "alerta";				endif;			endif;		else:			$mensaje = 'La informaci&oacute;n no se pudo actualizar';			$clase = 'error';		endif;		$_SESSION['resultado'] = array(			"mensaje"=>$mensaje,			"clase"=>$clase		);				$url_ref = $_POST['url_ref'];	endif;	/*delete*/	if(isset($_GET["haccion"]) && $_GET["haccion"]=="eliminar"):		$nid = mysql_real_escape_string($_GET['hid']);		$query = "SELECT nomArchivo FROM ctlg_usuarios WHERE idUser='{$nid}'";		$result = mysql_query($query);		$imagen = mysql_fetch_array($result);		$query = "DELETE FROM ctlg_usuarios WHERE idUser='{$nid}'";		$result = mysql_query($query);		if($result):			$mensaje = 'La informaci&oacute;n se elimino con exito';			$clase = 'exito';			if(file_exists("../".$carpeta_imagenes.'users/'.$nid.'_'.$imagen['nomArchivo'])):				@unlink("../".$carpeta_imagenes.'users/'.$nid.'_'.$imagen['nomArchivo']);			endif;		else:			$mensaje = 'La informaci&oacute;n no se pudo eliminar';			$clase = 'error';		endif;		$_SESSION['resultado'] = array(			"mensaje"=>$mensaje,			"clase"=>$clase		);	endif;	/*volvemos a la pagina*/	header("location:".$url_ref);?>